{
 "title": "ElasticSearch Cluster Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(elasticsearch_jvm_memory_max_bytes, instance)"
   },
   {
    "name": "nodename",
    "query": "label_values(elasticsearch_jvm_memory_max_bytes, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{instance=\"master01:9108\", color=\"green\"}"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "${nodename} Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "repeat": "nodename",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(elasticsearch_jvm_memory_used_bytes{area=\"heap\",name=\"$nodename\"} / elasticsearch_jvm_memory_max_bytes{area=\"heap\",name=\"$nodename\"}) * 100"
    }
   ]
  },
  {
   "title": "${nodename} Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(elasticsearch_jvm_memory_used_bytes{area=\"heap\",name=\"$nodename\"} / elasticsearch_jvm_memory_max_bytes{area=\"heap\",name=\"$nodename\"}) * 100"
    }
   ]
  },
  {
   "title": "${nodename} Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(elasticsearch_jvm_memory_used_bytes{area=\"heap\",name=\"$nodename\"} / elasticsearch_jvm_memory_max_bytes{area=\"heap\",name=\"$nodename\"}) * 100"
    }
   ]
  },
  {
   "title": "${nodename} Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(elasticsearch_jvm_memory_used_bytes{area=\"heap\",name=\"$nodename\"} / elasticsearch_jvm_memory_max_bytes{area=\"heap\",name=\"$nodename\"}) * 100"
    }
   ]
  },
  {
   "title": "$nodename CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "repeat": "nodename",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{name=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "$nodename CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{name=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "$nodename CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{name=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "$nodename CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{name=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "$nodename dIsk usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "repeat": "nodename",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-(elasticsearch_filesystem_data_available_bytes{name=\"$nodename\"}/elasticsearch_filesystem_data_size_bytes{name=\"$nodename\"})"
    }
   ]
  },
  {
   "title": "$nodename dIsk usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-(elasticsearch_filesystem_data_available_bytes{name=\"$nodename\"}/elasticsearch_filesystem_data_size_bytes{name=\"$nodename\"})"
    }
   ]
  },
  {
   "title": "$nodename dIsk usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-(elasticsearch_filesystem_data_available_bytes{name=\"$nodename\"}/elasticsearch_filesystem_data_size_bytes{name=\"$nodename\"})"
    }
   ]
  },
  {
   "title": "$nodename dIsk usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-(elasticsearch_filesystem_data_available_bytes{name=\"$nodename\"}/elasticsearch_filesystem_data_size_bytes{name=\"$nodename\"})"
    }
   ]
  }
 ]
}